#!/usr/bin/env ruby -wU

require 'circle/art'

token = ENV['CIRCLE_TOKEN']

unless token
  raise "Please set CIRCLE_TOKEN env variable. Visit https://circleci.com/account/api to get one"
end

repo  = ARGV[0]
build = ARGV[1]
pattern = ARGV[2]

puts "Download [#{pattern}] artifacts for Repo #{ARGV[0]}, Build ##{ARGV[1]}"

url = UrlBuilder.new(repo, build, token)

if File.exist?(url.json_path)
  puts "Load from local"
else
  puts "🌐  Getting CircleCI meta info"
  url.download_json!
end

parser = Parser.new(path: url.json_path, pattern: pattern)

url.download!(parser)

cuke = CukeBuilder.new(build, parser)
cuke.build_reports!